update

diff --git a/.github/workflows/trophy.yml b/.github/workflows/trophy.yml
--- a/.github/workflows/trophy.yml
+++ b/.github/workflows/trophy.yml
@@ -1,27 +1,43 @@
-name: Generate Trophy
+name: Generate GitHub Profile Trophy
 
 on:
   schedule:
-    - cron: "0 0 * * *" # Jalan otomatis setiap hari
+    - cron: "0 0 * * *" # Jalan otomatis setiap hari jam 12 malam UTC
+  push:
+    branches:
+      - main
+      - master
   workflow_dispatch:
 
 jobs:
-  build:
+  test-trophy:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout this repo
+        uses: actions/checkout@v4
 
-      - name: Generate trophy
+      - name: Test Action
+        id: trophy
         uses: Erik-Donath/github-profile-trophy@feature/generate-svg
         with:
-          username: Delta-Polder-Indonesia
-          output_path: trophy.svg
+          username: ${{ github.repository_owner }}
+          output_path: ./trophy.svg
           token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Verify SVG generated
+        run: |
+          if [ -f trophy.svg ]; then
+            echo "SVG exists ($(wc -c < trophy.svg) Bytes)"
+            file trophy.svg
+          else
+            echo "SVG failed to generate"
+            exit 1
+          fi
 
       - name: Commit & Push Trophy
         run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git add trophy.svg
-          git commit -m "Update GitHub Trophies" || exit 0
+          git commit -m "chore: update github profile trophies" || exit 0
           git push
